### ISSUE TITLE
请教一下，触控板使用不了

### ISSUE THREAD

**Issue by Qslting** [chiccheung/HP-Zhan66-Pro14-G2-macOS#1]
首先非常感谢，没遇到任何问题安装成功，我这边蓝牙正常，但是触控板用不了，请问应该怎么做呢？还有一个不懂的就是独立显卡说注入能屏蔽，能教下么？小白一枚！

**Comment by chiccheung** [comment]
使用最新版本，默认情况下独立显卡是屏蔽状态，触控板尝试执行以下命令：`sudo kextcache -i /` ，之后重启查看，我这边刚安装完也没有，后来执行了这个命令重启几次就好了。怀疑是这个清除缓存的命令起的作用，你帮忙测试一下，有结果反馈在这里就行。

**Comment by Qslting** [comment]
经过测试，触控板确实可以用了，而且可以三指切换屏幕，太牛了！就是当初就是为了玩玩硬盘才分配了40G，想在可玩性已经很高了！

**Comment by chiccheung** [comment]
> 经过测试，触控板确实可以用了，而且可以三指切换屏幕，太牛了！就是当初就是为了玩玩硬盘才分配了40G，想在可玩性已经很高了！

以后应该不会做太大的调整了，只会做一些更新性质的工作。
