### ISSUE TITLE
OC引导触摸板不能使用

### ISSUE THREAD

**Issue by tommy155** [chiccheung/HP-Zhan66-Pro14-G2-macOS#10]
双系统Mac Catalina + Windows 2019 LTSC
第一启动项为OC引导，进BIOS和Win10 触摸板不能用，是什么问题导致？

**Comment by stopyan** [comment]
本次更新的OC0.6.1for战66，完美解决了win10电池的识别错误。经查看触摸板和键盘相关SSDT发现没有针对windows系统做回避，导致给Mac OS的hotpatch同样在win10生效，从而造成win10触摸板功能异常。回头尝试修改再来更新。

**Comment by chiccheung** [comment]
> 本次更新的OC0.6.1for战66，完美解决了win10电池的识别错误。经查看触摸板和键盘相关SSDT发现没有针对windows系统做回避，导致给Mac OS的hotpatch同样在win10生效，从而造成win10触摸板功能异常。回头尝试修改再来更新。

SSDT里有系统判断语句，要出问题也是重命名出问题，Return Zero 的那个patch，估计重命名是对所有系统生效的。

**Comment by stopyan** [comment]
> > 本次更新的OC0.6.1for战66，完美解决了win10电池的识别错误。经查看触摸板和键盘相关SSDT发现没有针对windows系统做回避，导致给Mac OS的hotpatch同样在win10生效，从而造成win10触摸板功能异常。回头尝试修改再来更新。
> 
> SSDT里有系统判断语句，要出问题也是重命名出问题，Return Zero 的那个patch，估计重命名是对所有系统生效的。

重命名是对所有系统生效，于是SSDT的系统判断也需要有判断为windows之后定向到用来回避的被重命名走的部分

**Comment by stopyan** [comment]
Return Zero in _STA of TPD0，有时间的时候可以看看能否用带系统判断的方法来修改它

**Comment by chiccheung** [comment]
触摸板目前工作正常。
