### ISSUE TITLE
您好，我是HP ZHAN 99 Pro G1 MT台式机的黑苹果用户，想请教您一些问题。

### ISSUE THREAD

**Issue by Z-fly** [chiccheung/HP-Zhan66-Pro14-G2-macOS#11]
https://github.com/Z-fly/HP-ZHAN-99-Pro-G1-MT-Hackintosh
我这个配置目前10.15.7接近完美了，想请问下，如何把CLOVER的配置转换成OC？
还有这个配置能升到11吗？

**Comment by chiccheung** [comment]
> https://github.com/Z-fly/HP-ZHAN-99-Pro-G1-MT-Hackintosh
> 我这个配置目前10.15.7接近完美了，想请问下，如何把CLOVER的配置转换成OC？
> 还有这个配置能升到11吗？

- [从 Clover 到 OpenCore —— Clover 迁移 OpenCore 指南 By Sukka](https://blog.skk.moe/post/from-clover-to-opencore/)
- 是的，可以。

**Comment by Z-fly** [comment]
> > https://github.com/Z-fly/HP-ZHAN-99-Pro-G1-MT-Hackintosh
> > 我这个配置目前10.15.7接近完美了，想请问下，如何把CLOVER的配置转换成OC？
> > 还有这个配置能升到11吗？
> 
> * [从 Clover 到 OpenCore —— Clover 迁移 OpenCore 指南 By Sukka](https://blog.skk.moe/post/from-clover-to-opencore/)
> * 是的，可以。

那是转成OC升11还是直接升11？

**Comment by Z-fly** [comment]
@chiccheung

**Comment by stopyan** [comment]
> @chiccheung
暂时没有clover升级Mac os 11的经验。
实测OpenCore 0.6.3release 搭配当前最新release版本kext，稳定使用的战66二代笔记本EFI支持从10.15.7直接升级11.0.1，一切顺利。

**Comment by stopyan** [comment]
> > > https://github.com/Z-fly/HP-ZHAN-99-Pro-G1-MT-Hackintosh
> > > 我这个配置目前10.15.7接近完美了，想请问下，如何把CLOVER的配置转换成OC？
> > > 还有这个配置能升到11吗？
> > 
> > 
> > 
> > * [从 Clover 到 OpenCore —— Clover 迁移 OpenCore 指南 By Sukka](https://blog.skk.moe/post/from-clover-to-opencore/)
> > * 是的，可以。
> 
> 那是转成OC升11还是直接升11？

暂时没有clover升级Mac os 11的经验。
实测OpenCore 0.6.3release 搭配当前最新release版本kext，稳定使用的战66二代笔记本EFI支持从10.15.7直接升级11.0.1，一切顺利。

**Comment by Z-fly** [comment]
> > > > https://github.com/Z-fly/HP-ZHAN-99-Pro-G1-MT-Hackintosh
> > > > 我这个配置目前10.15.7接近完美了，想请问下，如何把CLOVER的配置转换成OC？
> > > > 还有这个配置能升到11吗？
> > > 
> > > 
> > > 
> > > * [从 Clover 到 OpenCore —— Clover 迁移 OpenCore 指南 By Sukka](https://blog.skk.moe/post/from-clover-to-opencore/)
> > > * 是的，可以。
> > 
> > 
> > 那是转成OC升11还是直接升11？
> 
> 暂时没有clover升级Mac os 11的经验。
> 实测OpenCore 0.6.3release 搭配当前最新release版本kext，稳定使用的战66二代笔记本EFI支持从10.15.7直接升级11.0.1，一切顺利。

感谢您回复。现在我的想法是，直接升级。但ZHAN 99 Pro G1 MT主板没有DP接口，恐怕升级完就黑屏了，而且全网都没有找到同样ZHAN 99黑苹果的人，不知道有没有人实验成功。我觉得无论clover还是OC，如果不能直接点亮，那就都没戏了，除非加张独立显卡。

**Comment by Z-fly** [comment]
http://bbs.pcbeta.com/viewthread-1875857-1-1.html
看了这个帖子，他说clover底层变成oc了。
我想问下，在线升级之后所有注入的驱动全都会丢失吗？

**Comment by chiccheung** [comment]
> http://bbs.pcbeta.com/viewthread-1875857-1-1.html
> 看了这个帖子，他说clover底层变成oc了。
> 我想问下，在线升级之后所有注入的驱动全都会丢失吗？

[OpenCore 简体中文参考手册](https://oc.skk.moe/)
