### ISSUE TITLE
webcam

### ISSUE THREAD

**Issue by jcheunglin** [chiccheung/HP-Zhan66-Pro14-G2-macOS#4]
这款战66带不带红外摄像头，就是windows hello，摄像头在mac下面能工作吗

**Comment by FearwareX** [comment]
不带哦

**Comment by jcheunglin** [comment]
好的b（￣▽￣）d　，我是elitebook 830，带红外的摄像头，死活没法驱动相机 ，对比了能驱动的版本，唯一区别在带不带红外，所以来咨询一下，谢啦

**Comment by chiccheung** [comment]
普通摄像头，macOS 下正常工作
