### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by hardwork-anytime** [chiccheung/HP-Zhan66-Pro14-G2-macOS#9]
大佬定制的oc0.5.9，在10.15.6版本的系统中，第二次自动睡眠必睡死，长时间盒盖睡眠会关机或者打开后唤醒不了屏幕，点击报告显示：
Sleep Wake failure in EFI

Failure code:: 0x00000000 0x0000001f

**Comment by chiccheung** [comment]
> 大佬定制的oc0.5.9，在10.15.6版本的系统中，第二次自动睡眠必睡死，长时间盒盖睡眠会关机或者打开后唤醒不了屏幕，点击报告显示：
> Sleep Wake failure in EFI
> 
> Failure code:: 0x00000000 0x0000001f

已修补

**Comment by aliyoge** [comment]
> > 大佬定制的oc0.5.9，在10.15.6版本的系统中，第二次自动睡眠必睡死，长时间盒盖睡眠会关机或者打开后唤醒不了屏幕，点击报告显示：
> > Sleep Wake failure in EFI
> > 
> > Failure code:: 0x00000000 0x0000001f
> 
> 已修补

请问你是怎样修复这个问题的，我这边出现这个问题，型号是战66 13 Pro i7。
